repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
    - id: flake8
      args:
      - '--ignore'
      - 'E501,W503, E203'
  - repo: https://github.com/python/mypy
    rev: master
    hooks:
      - id: mypy
        args:
        - "src"
