[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.

[tool.pytest.ini_options]
testpaths = ["test"]

[tool.coverage.run]
source = ['src']