name: Publish to PYPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip setuptools build twine
    - name: Build
      run: |
        python -m build
    - name: Check packages
      run: |
        python -m twine check
    - name: Publish
      run: |
        python -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
