name: Test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install -r dev_requirements.txt
    - name: unittest
      run: |
        pytest --cov
    - name: Coveralls coverage submission
      uses: coverallsapp/github-action@v2

